# Generated by Django 6.0.6 on 2026-07-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Watch', 'Watch'), ('Headphone', 'Headphone'), ('TV', 'TV')], max_length=50),
        ),
    ]
